# Generated by Django 4.1.6 on 2023-02-12 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="manufacturer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cars",
                to="core.manufacturer",
                verbose_name="Fabricante",
            ),
        ),
        migrations.AlterField(
            model_name="city",
            name="state",
            field=models.ManyToManyField(to="core.state", verbose_name="Estado"),
        ),
    ]
